/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ShishGrupipka } from './ShishGrupipka';
export * as factories from './factories';
export { ShishGrupipka__factory } from './factories/ShishGrupipka__factory';
